# POST http://localhost:3000/signup
# Content-Type: application/json

# {
#     "fullname": "Kunaal",
#     "email": "kunaa@gmail.com",
#     "password": "Kunaal1"
# }

POST http://localhost:3000/signin 
Content-Type: application/json

{
    "email": "kunaal@gmail.com",
    "password": "Kunaal"
}

